package com.example.proyecto_genshiken

object Curiosidades {
    val lista = listOf(
        "¿Sabías que la espada más antigua tiene más de 5000 años?",
        "¿Sabías que Yuma Kokohead saca su espada de la boca de una shinigami?",
        "¿Sabías que Meliodas no consigue su icónica espada hasta la temporada 2?",
        "¿Sabías que esta APP la han desarrollado dos chavales de prácticas?",
        "¿Sabías que si haces Miximax con el rey Arturo puedes blandir Excallibur?",
        "¿Sabías que es ilegal jugar al futbol con una espada en la mano?",
        "¿Sabías que Miwa ya no puede blandir otra espada que no sea la suya?",
        "¿Sabías que no se debe agarrar una espada por el filo?",
        "¿Sabías que Meliodas hizo un Full Counter con una cucharilla?",
        "¿Sabías que si Superman y Goku se encontrarán, no se entenderían?",
        "¿Sabías que Yuji Itadori rompe su Cuchillo en el episodio 3?",
        "¿Sabías que Nobara Kugisaki ha tenido más de un martillo?",
        "¿Sabías que los clones de Twice nacen con ropa?",
        "¿Sabías que la katana de Peko Pekoyama es de bambú?",
        "¿Sabías que nunca vemos el aspecto real de la espada de Kento Nanami?",
        "¿Sabías que en Shibuya nunca hubo un incidente relacionado a maldiciones?",
        "¿Sabías que en Nanatsu no Taizai muchos personajes tienen técnicas muy convenientes para la trama?",
        "¿Sabías que cuando suena la música de la intro en una batalla significa que la van a ganar los protagonistas?",
        "¿Sabías que nunca hubo un partido entre la sub-20 y los jugadores de Blue Lock?",
        "¿Sabías que la Shogun Raiden saca su espada de su pecho y no de entre sus pechos?",
        "¿Sabías que Lisa de Genshin Impact tiene los ojos verdes? a ver donde miramos...",
        "¿Sabías que Skirk no es canónicamente del elemento cryo?",
        "¿Sabías que Satoru Gojo no tiene los Seis Ojos? Solamente tiene 2",
        "¿Sabías que Toji Fushiguro tiene un brazo del 45?",
        "¿Sabías que en algún lugar del mundo a Toji Fushiguro le conocerán como El Chambas?",
        "¿Sabías que La reliquia sagrada Lostvayne vale lo mismo que el Boar Hat?",
        "¿Sabías que en Fate Stay Night: Unlimited Blade Works, Arturo solamente usa una vez su Noble Fantasma?",
        "¿Sabías que en Fate Stay Night: Unlimited Blade Works, no aparecen Blades ilimitados trabajando?",
        "¿Sabías que de las cinco personas, tres deben pagar?",
        "¿Sabías que Makoto Naegi obliga a los demás personajes a repetir sus diálogos si es que no encuentra una contradiccion?",
        "¿Sabías que Galand de la Verdad solamente recibe un golpe del Tesoro Sagrado Rita?",
        "¿Sabías que puedes usar una espada en vez de un cuchillo para cortar?",
        "¿Sabías que las katanas son en realidad muy frágiles si no se usan bien?",
        "¿Sabías que el famoso duelo a muerte con cuchillos en realidad no fue un duelo a muerte con cuchillos?",
        "¿Sabías que en Kimetsu no Yaiba los efectos visuales tras realizar las posturas son en realidad imaginaciones?",
        "¿Sabías que si Stain se corta la lengua se quedaría paralizado para siempre?",
        "¿Sabías que el live action de One Piece no es real?",
        "¿Sabías que el One Piece son los amigos que hicimos por el camino? ¿Qué? ¿Qué ese meme ya ha sido muy explotado? Bueno... ¡Ponte tu a hacer datos curiosos! Ya verás que difícil es",
        "¿Sabías que hay 33550336 razones para llorar sin motivo alguno? ",
        "¿Sabías que Spinner es el único villano de My Hero Academia que no muere?",
        "¿Sabías que en el Bosque Verde habitan pokemon extremadamente letales para el ser humano?",
        "¿Sabías que el equipo del Raimon en realidad se llama El Tori?",
        "¿Sabías quien le dio el paraguas a Maria? De verdad... ¿Quién se lo dió?",
        "¿Sabías que Megumi Fushiguro casi invoca a Mahoraga tras darse cuenta de que el examen tenía parte de atrás?",
        "Cheesecak 🤤",
        "¿Sabías que en términos de reproducción entre humanos y Pokemon, Vaporeon... \n Mostrar más",
        "¿Sabías que no es recomendable apagar incendios como lo hacen en Fire Force?",
        "¿Sabías que esta será una historia romántica como nunca antes se había contado?",
        "¿Sabías que Momo Yoyorouzu puede acabar con la economía global?",
        "¿Sabías que Kaede Akamatsu no es matemática ni física? ahí lo dejo...",
        "¿Sabías que el famoso meme de Kyoko Kirigiri siendo ejecutada es la unica ejecución no canon de Danganronpa?",
        "¿Sabías que no deberías intentar asesinar a tu profesor? a menos que sea un alien...",
        "¿Sabías que el Karasuno no es un equipo de Voleibol real?",
        "¿Sabías que el campo de fútbol de Capitán Tsubasa mide como 3 países de largo?",
        "¿Sabías que las espadas en la vida real no son tan extravagantes como lo hacen en los Animes?",
        "¿Sabías que el Hara-Kiri era el 67 de la época en Japón?",
        "¿Sabías que lootear a un viejo muerto te dá los poderes de la Armonía?",
        "¿Sabías que en Wuthering Waves, el protagonista no suele volver a hablar con ningun personaje de la historia tras haber acabado la msisión principal de turno?",
        "¿Sabías que en Persona 5, casi todas tus decisiones las tiene que aprobar un gato?",
        "¿Sabías que Sung Jin-Woo y Dwayne Johnson tienen el mismo contrato?",
        "¿Sabías que Brad Pitt será la voz de Klee en el Anime de Genshin Impact?",
        "¿Sabías que en Danganronpa no es muy recomendable tener un arco de personaje?",
        "¿Sabías que tus desgracias no son cosa de un Yo-Kai? ¡deja de culpar a Ayay!",
        "¿Sabías que los juicios normales no son como los de Ace Attorney? lo descubrí por las malas...",
        "¿Sabías que cualquier lugar se ve más bonito si decimos que está en Japón?",
        "¿Sabías que en Inazuma Eleven 2 hay un texto en el que no recomiendan imitar las supertécnicas? y yo que ya tenía los pinguinos...",
        "¿Sabías que nunca voy a abandonarte, nunca te decepcionaré, nunca andaré de vago ni te abandonaré?",
        "¿Sabías que existe un Anime de la Biblia? Parece ser que el episodio donde Jesus muere tuvo malas críticas y el autor decidió revivirlo... Que conveniencia del guión",
        "¿Sabías que existe un concepto universal en internet donde aparece FranYaoi en cualquier lado?",
        "¿Sabías que el otro día vi Boku No Pico? Buah, pedazo de serie, me gusta el rubio, pero aun no entiendo donde esta la temática de superhéroes ¿Y quíen es Deku? ¿Será que aparece en la siguiente temporada?",
        "¿Sabes que juego hizo Willyrex? ¡RESPONDE A LA PREGUNTA! ¡¿QUÉ JUEGO HIZO WILLYREX!?",
        "¿Sabías que hay personas a las que les hace gracia el numero 7? Y también el color azul, y los zapatos, y que las chicas solo valgan 1. De las dos personas que hayan difundido eso, uno debe de tener unos testículos muy débiles y llamarse Marcos, mientras que el otro debe de ser un mitómano furro ladrón de pozos. Que específico ¿Verdad? ",
        "¿Sabías que El Castillo Infinito de Kimetsu No Yaiba no era tan infinito? Ahora que lo pienso el tren tampoco era tan infinito...",
        "¿Sabías que Naruto se imagina a Sasuke después de ver a un hombre desnudo en unos baños? 🤨🏳️‍🌈?",
        "¿Sabías que si en Persona 5 no prestas atención a las clases, seguramente suspenderás los examenes? ¡Es como la vida real!",
        "¿Sabías que en My Hero Academia, ningún villano acaba recordando a Magnet?",
        "¿Sabías que MiHoyo solo me da disgustos? Siempre acaba traicionandome cuando menos me lo espero...",
        "¿Sabías que mucha gente se compró el Resident Evil VIII solo por Lady Dimitrescu? casualmente uno de los mods más populares es el del matamoscas",
        "Sabías que en Danganronpa, por mucho que el asesino confiese y grite, o se demuestre que Makoto tenía coartada, si fallas mucho, todo el mundo pensará que el asesino fue Makoto y le votarán",
        "¿Sabías que en Wuthering Waves, si pisas la academía, tu dispositivo literalmente arde?",
        "¿Sabías que Zenless Zone Zero no esconde que hay una toda una subtrama de tráfico de organos en Nueva Eridu?",
        "¿Sabías que casi nadie sabe como se escribe 'Monsdtadt?' ¿O era Mondstadt? ¿Quiza Monstat...? ¡Bah! Seguro que el nombre de la región de cryo es más facil de escribir",
        "¿Sabías que esto no es un Short? no como los vídeos de cierto noruego",
        "¿Sabiás que en el mundo de Super Mario todos son amigos? Por muchos secuestros que hayan, al final todos acaban yendo a jugar al tenis o a las carreras. Aunque ironicamente todo tiene el nombre de mario... Mario Kart, Mario Tenis, Mario Party... \n Que egocéntrico ¿No?",
        "¿Sabías que Hogwarts es el lugar más seguro del mundo?",
        "¿Sabías que soi un vanpiro cristina?",
        "¿Sabías que Rudeus está incluso más perturbado que Kazuma? Creeme que si...",
        "¿Sabías que existe un fanfic de Death Note cuyo protagonista es Dark Yagami? es... curioso cuanto menos",
        "¿Sabías que este juego no esta traducido al inglés porque no encaja dentro de mi visión creativa?",
        "¿Sabías que no puedo amarte? No porque seas un conejo, sino porque eres neg-"





    )
}